name: Sunveer - Paul
favicon: null
layout_spectrum: 0.91064
typography_spectrum: 0.30896895728074014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6187563086859882
  lightness: 0.037454519886523485
  saturation: 0.3048190684057772
  rhythmicContrast: 0.7268575050402433
purpose: []
